development: &development
  ws_url: "http://localhost:4000"
  ps_url: "http://localhost:4000"
  return_to: "http://localhost:4000/success"
  email: your-email@pagseguro.com
  token: "your-pagseguro-key-here"

test:
  <<: *development

production:
  <<: *development